// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: lsp.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Gauge.Messages {

  /// <summary>Holder for reflection information generated from lsp.proto</summary>
  public static partial class LspReflection {

    #region Descriptor
    /// <summary>File descriptor for lsp.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LspReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cglsc3AucHJvdG8SDmdhdWdlLm1lc3NhZ2VzGg5tZXNzYWdlcy5wcm90bzKc",
            "BwoKbHNwU2VydmljZRJYCgxHZXRTdGVwTmFtZXMSIC5nYXVnZS5tZXNzYWdl",
            "cy5TdGVwTmFtZXNSZXF1ZXN0GiEuZ2F1Z2UubWVzc2FnZXMuU3RlcE5hbWVz",
            "UmVzcG9uc2UiA4gCARJJCglDYWNoZUZpbGUSIC5nYXVnZS5tZXNzYWdlcy5D",
            "YWNoZUZpbGVSZXF1ZXN0GhUuZ2F1Z2UubWVzc2FnZXMuRW1wdHkiA4gCARJk",
            "ChBHZXRTdGVwUG9zaXRpb25zEiQuZ2F1Z2UubWVzc2FnZXMuU3RlcFBvc2l0",
            "aW9uc1JlcXVlc3QaJS5nYXVnZS5tZXNzYWdlcy5TdGVwUG9zaXRpb25zUmVz",
            "cG9uc2UiA4gCARJkChZHZXRJbXBsZW1lbnRhdGlvbkZpbGVzEhUuZ2F1Z2Uu",
            "bWVzc2FnZXMuRW1wdHkaLi5nYXVnZS5tZXNzYWdlcy5JbXBsZW1lbnRhdGlv",
            "bkZpbGVMaXN0UmVzcG9uc2UiA4gCARJdCg1JbXBsZW1lbnRTdHViEi0uZ2F1",
            "Z2UubWVzc2FnZXMuU3R1YkltcGxlbWVudGF0aW9uQ29kZVJlcXVlc3QaGC5n",
            "YXVnZS5tZXNzYWdlcy5GaWxlRGlmZiIDiAIBEl4KDFZhbGlkYXRlU3RlcBIj",
            "LmdhdWdlLm1lc3NhZ2VzLlN0ZXBWYWxpZGF0ZVJlcXVlc3QaJC5nYXVnZS5t",
            "ZXNzYWdlcy5TdGVwVmFsaWRhdGVSZXNwb25zZSIDiAIBElIKCFJlZmFjdG9y",
            "Eh8uZ2F1Z2UubWVzc2FnZXMuUmVmYWN0b3JSZXF1ZXN0GiAuZ2F1Z2UubWVz",
            "c2FnZXMuUmVmYWN0b3JSZXNwb25zZSIDiAIBElUKC0dldFN0ZXBOYW1lEh8u",
            "Z2F1Z2UubWVzc2FnZXMuU3RlcE5hbWVSZXF1ZXN0GiAuZ2F1Z2UubWVzc2Fn",
            "ZXMuU3RlcE5hbWVSZXNwb25zZSIDiAIBEmQKD0dldEdsb2JQYXR0ZXJucxIV",
            "LmdhdWdlLm1lc3NhZ2VzLkVtcHR5GjUuZ2F1Z2UubWVzc2FnZXMuSW1wbGVt",
            "ZW50YXRpb25GaWxlR2xvYlBhdHRlcm5SZXNwb25zZSIDiAIBEk0KC0tpbGxQ",
            "cm9jZXNzEiIuZ2F1Z2UubWVzc2FnZXMuS2lsbFByb2Nlc3NSZXF1ZXN0GhUu",
            "Z2F1Z2UubWVzc2FnZXMuRW1wdHkiA4gCAUJcChZjb20udGhvdWdodHdvcmtz",
            "LmdhdWdlWjFnaXRodWIuY29tL2dldGdhdWdlL2dhdWdlLXByb3RvL2dvL2dh",
            "dWdlX21lc3NhZ2VzqgIOR2F1Z2UuTWVzc2FnZXNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Gauge.Messages.MessagesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
