// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: lsp.proto
// </auto-generated>
// Original file comments:
// ----------------------------------------------------------------
//  Copyright (c) ThoughtWorks, Inc.
//  Licensed under the Apache License, Version 2.0
//  See LICENSE in the project root for license information.
// ----------------------------------------------------------------
//
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Gauge.Messages {
  public static partial class lspService
  {
    static readonly string __ServiceName = "gauge.messages.lspService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Gauge.Messages.StepNamesRequest> __Marshaller_gauge_messages_StepNamesRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Gauge.Messages.StepNamesRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Gauge.Messages.StepNamesResponse> __Marshaller_gauge_messages_StepNamesResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Gauge.Messages.StepNamesResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Gauge.Messages.CacheFileRequest> __Marshaller_gauge_messages_CacheFileRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Gauge.Messages.CacheFileRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Gauge.Messages.Empty> __Marshaller_gauge_messages_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Gauge.Messages.Empty.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Gauge.Messages.StepPositionsRequest> __Marshaller_gauge_messages_StepPositionsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Gauge.Messages.StepPositionsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Gauge.Messages.StepPositionsResponse> __Marshaller_gauge_messages_StepPositionsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Gauge.Messages.StepPositionsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Gauge.Messages.ImplementationFileListResponse> __Marshaller_gauge_messages_ImplementationFileListResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Gauge.Messages.ImplementationFileListResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Gauge.Messages.StubImplementationCodeRequest> __Marshaller_gauge_messages_StubImplementationCodeRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Gauge.Messages.StubImplementationCodeRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Gauge.Messages.FileDiff> __Marshaller_gauge_messages_FileDiff = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Gauge.Messages.FileDiff.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Gauge.Messages.StepValidateRequest> __Marshaller_gauge_messages_StepValidateRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Gauge.Messages.StepValidateRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Gauge.Messages.StepValidateResponse> __Marshaller_gauge_messages_StepValidateResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Gauge.Messages.StepValidateResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Gauge.Messages.RefactorRequest> __Marshaller_gauge_messages_RefactorRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Gauge.Messages.RefactorRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Gauge.Messages.RefactorResponse> __Marshaller_gauge_messages_RefactorResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Gauge.Messages.RefactorResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Gauge.Messages.StepNameRequest> __Marshaller_gauge_messages_StepNameRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Gauge.Messages.StepNameRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Gauge.Messages.StepNameResponse> __Marshaller_gauge_messages_StepNameResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Gauge.Messages.StepNameResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Gauge.Messages.ImplementationFileGlobPatternResponse> __Marshaller_gauge_messages_ImplementationFileGlobPatternResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Gauge.Messages.ImplementationFileGlobPatternResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Gauge.Messages.KillProcessRequest> __Marshaller_gauge_messages_KillProcessRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Gauge.Messages.KillProcessRequest.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Gauge.Messages.StepNamesRequest, global::Gauge.Messages.StepNamesResponse> __Method_GetStepNames = new grpc::Method<global::Gauge.Messages.StepNamesRequest, global::Gauge.Messages.StepNamesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetStepNames",
        __Marshaller_gauge_messages_StepNamesRequest,
        __Marshaller_gauge_messages_StepNamesResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Gauge.Messages.CacheFileRequest, global::Gauge.Messages.Empty> __Method_CacheFile = new grpc::Method<global::Gauge.Messages.CacheFileRequest, global::Gauge.Messages.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CacheFile",
        __Marshaller_gauge_messages_CacheFileRequest,
        __Marshaller_gauge_messages_Empty);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Gauge.Messages.StepPositionsRequest, global::Gauge.Messages.StepPositionsResponse> __Method_GetStepPositions = new grpc::Method<global::Gauge.Messages.StepPositionsRequest, global::Gauge.Messages.StepPositionsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetStepPositions",
        __Marshaller_gauge_messages_StepPositionsRequest,
        __Marshaller_gauge_messages_StepPositionsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Gauge.Messages.Empty, global::Gauge.Messages.ImplementationFileListResponse> __Method_GetImplementationFiles = new grpc::Method<global::Gauge.Messages.Empty, global::Gauge.Messages.ImplementationFileListResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetImplementationFiles",
        __Marshaller_gauge_messages_Empty,
        __Marshaller_gauge_messages_ImplementationFileListResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Gauge.Messages.StubImplementationCodeRequest, global::Gauge.Messages.FileDiff> __Method_ImplementStub = new grpc::Method<global::Gauge.Messages.StubImplementationCodeRequest, global::Gauge.Messages.FileDiff>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ImplementStub",
        __Marshaller_gauge_messages_StubImplementationCodeRequest,
        __Marshaller_gauge_messages_FileDiff);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Gauge.Messages.StepValidateRequest, global::Gauge.Messages.StepValidateResponse> __Method_ValidateStep = new grpc::Method<global::Gauge.Messages.StepValidateRequest, global::Gauge.Messages.StepValidateResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ValidateStep",
        __Marshaller_gauge_messages_StepValidateRequest,
        __Marshaller_gauge_messages_StepValidateResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Gauge.Messages.RefactorRequest, global::Gauge.Messages.RefactorResponse> __Method_Refactor = new grpc::Method<global::Gauge.Messages.RefactorRequest, global::Gauge.Messages.RefactorResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Refactor",
        __Marshaller_gauge_messages_RefactorRequest,
        __Marshaller_gauge_messages_RefactorResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Gauge.Messages.StepNameRequest, global::Gauge.Messages.StepNameResponse> __Method_GetStepName = new grpc::Method<global::Gauge.Messages.StepNameRequest, global::Gauge.Messages.StepNameResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetStepName",
        __Marshaller_gauge_messages_StepNameRequest,
        __Marshaller_gauge_messages_StepNameResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Gauge.Messages.Empty, global::Gauge.Messages.ImplementationFileGlobPatternResponse> __Method_GetGlobPatterns = new grpc::Method<global::Gauge.Messages.Empty, global::Gauge.Messages.ImplementationFileGlobPatternResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetGlobPatterns",
        __Marshaller_gauge_messages_Empty,
        __Marshaller_gauge_messages_ImplementationFileGlobPatternResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Gauge.Messages.KillProcessRequest, global::Gauge.Messages.Empty> __Method_KillProcess = new grpc::Method<global::Gauge.Messages.KillProcessRequest, global::Gauge.Messages.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "KillProcess",
        __Marshaller_gauge_messages_KillProcessRequest,
        __Marshaller_gauge_messages_Empty);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Gauge.Messages.LspReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of lspService</summary>
    [grpc::BindServiceMethod(typeof(lspService), "BindService")]
    public abstract partial class lspServiceBase
    {
      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Gauge.Messages.StepNamesResponse> GetStepNames(global::Gauge.Messages.StepNamesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Gauge.Messages.Empty> CacheFile(global::Gauge.Messages.CacheFileRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Gauge.Messages.StepPositionsResponse> GetStepPositions(global::Gauge.Messages.StepPositionsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Gauge.Messages.ImplementationFileListResponse> GetImplementationFiles(global::Gauge.Messages.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Gauge.Messages.FileDiff> ImplementStub(global::Gauge.Messages.StubImplementationCodeRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Gauge.Messages.StepValidateResponse> ValidateStep(global::Gauge.Messages.StepValidateRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Gauge.Messages.RefactorResponse> Refactor(global::Gauge.Messages.RefactorRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Gauge.Messages.StepNameResponse> GetStepName(global::Gauge.Messages.StepNameRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Gauge.Messages.ImplementationFileGlobPatternResponse> GetGlobPatterns(global::Gauge.Messages.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Gauge.Messages.Empty> KillProcess(global::Gauge.Messages.KillProcessRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for lspService</summary>
    public partial class lspServiceClient : grpc::ClientBase<lspServiceClient>
    {
      /// <summary>Creates a new client for lspService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public lspServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for lspService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public lspServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected lspServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected lspServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Gauge.Messages.StepNamesResponse GetStepNames(global::Gauge.Messages.StepNamesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetStepNames(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Gauge.Messages.StepNamesResponse GetStepNames(global::Gauge.Messages.StepNamesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetStepNames, null, options, request);
      }
      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Gauge.Messages.StepNamesResponse> GetStepNamesAsync(global::Gauge.Messages.StepNamesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetStepNamesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Gauge.Messages.StepNamesResponse> GetStepNamesAsync(global::Gauge.Messages.StepNamesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetStepNames, null, options, request);
      }
      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Gauge.Messages.Empty CacheFile(global::Gauge.Messages.CacheFileRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CacheFile(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Gauge.Messages.Empty CacheFile(global::Gauge.Messages.CacheFileRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CacheFile, null, options, request);
      }
      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Gauge.Messages.Empty> CacheFileAsync(global::Gauge.Messages.CacheFileRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CacheFileAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Gauge.Messages.Empty> CacheFileAsync(global::Gauge.Messages.CacheFileRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CacheFile, null, options, request);
      }
      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Gauge.Messages.StepPositionsResponse GetStepPositions(global::Gauge.Messages.StepPositionsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetStepPositions(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Gauge.Messages.StepPositionsResponse GetStepPositions(global::Gauge.Messages.StepPositionsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetStepPositions, null, options, request);
      }
      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Gauge.Messages.StepPositionsResponse> GetStepPositionsAsync(global::Gauge.Messages.StepPositionsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetStepPositionsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Gauge.Messages.StepPositionsResponse> GetStepPositionsAsync(global::Gauge.Messages.StepPositionsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetStepPositions, null, options, request);
      }
      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Gauge.Messages.ImplementationFileListResponse GetImplementationFiles(global::Gauge.Messages.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetImplementationFiles(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Gauge.Messages.ImplementationFileListResponse GetImplementationFiles(global::Gauge.Messages.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetImplementationFiles, null, options, request);
      }
      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Gauge.Messages.ImplementationFileListResponse> GetImplementationFilesAsync(global::Gauge.Messages.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetImplementationFilesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Gauge.Messages.ImplementationFileListResponse> GetImplementationFilesAsync(global::Gauge.Messages.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetImplementationFiles, null, options, request);
      }
      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Gauge.Messages.FileDiff ImplementStub(global::Gauge.Messages.StubImplementationCodeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ImplementStub(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Gauge.Messages.FileDiff ImplementStub(global::Gauge.Messages.StubImplementationCodeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ImplementStub, null, options, request);
      }
      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Gauge.Messages.FileDiff> ImplementStubAsync(global::Gauge.Messages.StubImplementationCodeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ImplementStubAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Gauge.Messages.FileDiff> ImplementStubAsync(global::Gauge.Messages.StubImplementationCodeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ImplementStub, null, options, request);
      }
      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Gauge.Messages.StepValidateResponse ValidateStep(global::Gauge.Messages.StepValidateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ValidateStep(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Gauge.Messages.StepValidateResponse ValidateStep(global::Gauge.Messages.StepValidateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ValidateStep, null, options, request);
      }
      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Gauge.Messages.StepValidateResponse> ValidateStepAsync(global::Gauge.Messages.StepValidateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ValidateStepAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Gauge.Messages.StepValidateResponse> ValidateStepAsync(global::Gauge.Messages.StepValidateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ValidateStep, null, options, request);
      }
      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Gauge.Messages.RefactorResponse Refactor(global::Gauge.Messages.RefactorRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Refactor(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Gauge.Messages.RefactorResponse Refactor(global::Gauge.Messages.RefactorRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Refactor, null, options, request);
      }
      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Gauge.Messages.RefactorResponse> RefactorAsync(global::Gauge.Messages.RefactorRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RefactorAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Gauge.Messages.RefactorResponse> RefactorAsync(global::Gauge.Messages.RefactorRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Refactor, null, options, request);
      }
      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Gauge.Messages.StepNameResponse GetStepName(global::Gauge.Messages.StepNameRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetStepName(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Gauge.Messages.StepNameResponse GetStepName(global::Gauge.Messages.StepNameRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetStepName, null, options, request);
      }
      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Gauge.Messages.StepNameResponse> GetStepNameAsync(global::Gauge.Messages.StepNameRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetStepNameAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Gauge.Messages.StepNameResponse> GetStepNameAsync(global::Gauge.Messages.StepNameRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetStepName, null, options, request);
      }
      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Gauge.Messages.ImplementationFileGlobPatternResponse GetGlobPatterns(global::Gauge.Messages.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetGlobPatterns(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Gauge.Messages.ImplementationFileGlobPatternResponse GetGlobPatterns(global::Gauge.Messages.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetGlobPatterns, null, options, request);
      }
      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Gauge.Messages.ImplementationFileGlobPatternResponse> GetGlobPatternsAsync(global::Gauge.Messages.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetGlobPatternsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Gauge.Messages.ImplementationFileGlobPatternResponse> GetGlobPatternsAsync(global::Gauge.Messages.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetGlobPatterns, null, options, request);
      }
      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Gauge.Messages.Empty KillProcess(global::Gauge.Messages.KillProcessRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return KillProcess(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Gauge.Messages.Empty KillProcess(global::Gauge.Messages.KillProcessRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_KillProcess, null, options, request);
      }
      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Gauge.Messages.Empty> KillProcessAsync(global::Gauge.Messages.KillProcessRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return KillProcessAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.ObsoleteAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Gauge.Messages.Empty> KillProcessAsync(global::Gauge.Messages.KillProcessRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_KillProcess, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override lspServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new lspServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(lspServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetStepNames, serviceImpl.GetStepNames)
          .AddMethod(__Method_CacheFile, serviceImpl.CacheFile)
          .AddMethod(__Method_GetStepPositions, serviceImpl.GetStepPositions)
          .AddMethod(__Method_GetImplementationFiles, serviceImpl.GetImplementationFiles)
          .AddMethod(__Method_ImplementStub, serviceImpl.ImplementStub)
          .AddMethod(__Method_ValidateStep, serviceImpl.ValidateStep)
          .AddMethod(__Method_Refactor, serviceImpl.Refactor)
          .AddMethod(__Method_GetStepName, serviceImpl.GetStepName)
          .AddMethod(__Method_GetGlobPatterns, serviceImpl.GetGlobPatterns)
          .AddMethod(__Method_KillProcess, serviceImpl.KillProcess).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, lspServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetStepNames, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Gauge.Messages.StepNamesRequest, global::Gauge.Messages.StepNamesResponse>(serviceImpl.GetStepNames));
      serviceBinder.AddMethod(__Method_CacheFile, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Gauge.Messages.CacheFileRequest, global::Gauge.Messages.Empty>(serviceImpl.CacheFile));
      serviceBinder.AddMethod(__Method_GetStepPositions, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Gauge.Messages.StepPositionsRequest, global::Gauge.Messages.StepPositionsResponse>(serviceImpl.GetStepPositions));
      serviceBinder.AddMethod(__Method_GetImplementationFiles, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Gauge.Messages.Empty, global::Gauge.Messages.ImplementationFileListResponse>(serviceImpl.GetImplementationFiles));
      serviceBinder.AddMethod(__Method_ImplementStub, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Gauge.Messages.StubImplementationCodeRequest, global::Gauge.Messages.FileDiff>(serviceImpl.ImplementStub));
      serviceBinder.AddMethod(__Method_ValidateStep, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Gauge.Messages.StepValidateRequest, global::Gauge.Messages.StepValidateResponse>(serviceImpl.ValidateStep));
      serviceBinder.AddMethod(__Method_Refactor, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Gauge.Messages.RefactorRequest, global::Gauge.Messages.RefactorResponse>(serviceImpl.Refactor));
      serviceBinder.AddMethod(__Method_GetStepName, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Gauge.Messages.StepNameRequest, global::Gauge.Messages.StepNameResponse>(serviceImpl.GetStepName));
      serviceBinder.AddMethod(__Method_GetGlobPatterns, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Gauge.Messages.Empty, global::Gauge.Messages.ImplementationFileGlobPatternResponse>(serviceImpl.GetGlobPatterns));
      serviceBinder.AddMethod(__Method_KillProcess, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Gauge.Messages.KillProcessRequest, global::Gauge.Messages.Empty>(serviceImpl.KillProcess));
    }

  }
}
#endregion
